added joke feature
DSC-SIST/Discord-Bot pull request #26
Opened 2021-04-05 08:45 UTC by rajiv8

## Added joke functionality..

2021-04-07 06:31 UTC, KamalDGRT commented on app.py
> +    url = request.urlopen("https://official-joke-api.appspot.com/jokes/programming/random")
Lets have the URL in the `.env` file.

2021-04-07 06:33 UTC, KamalDGRT requested changes

2021-04-07 06:33 UTC, KamalDGRT commented on app.py
> +import json
We usually import the packages in the ascending order.

2021-04-07 09:08 UTC, rajiv8 commented on app.py
> +    url = request.urlopen("https://official-joke-api.appspot.com/jokes/programming/random")
DONE , Please Check .

2021-04-11 03:59 UTC, KamalDGRT commented
Closing this PR as we are going with a new file structure.

2021-04-11 03:59 UTC, closed without merging